# Generated by Django 2.2 on 2019-12-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='user',
            new_name='users',
        ),
    ]
