# Generated by Django 2.2 on 2019-12-13 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('dash_app', '0002_auto_20191213_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='users',
        ),
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='login_app.User'),
            preserve_default=False,
        ),
    ]
