# Generated by Django 2.2 on 2019-12-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('dash_app', '0006_auto_20191213_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='updated_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='update_trips', to='login_app.User'),
            preserve_default=False,
        ),
    ]
