# Generated by Django 2.2 on 2019-12-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_app', '0002_auto_20191211_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='TV_showsManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
