# Generated by Django 2.2 on 2019-12-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TV_app', '0003_tv_showsmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TV_showsManager',
        ),
    ]
