# Generated by Django 2.2 on 2019-12-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
